# tasks_metrics.py
# Associação de perguntas por tipo de tarefa: gestao_despensa, receitas, lista_compras

tasks_metrics = {
    "lista_compras": [
        "Já teve dificuldade em fazer o assistente entender que queria adicionar algo à lista?",
        "Conseguiu adicionar itens com quantidades específicas (ex: 2 tomates, 1 kg de arroz)?",
        "A funcionalidade da lista de compras é útil no seu dia a dia?",
        "Já sentiu frustração ao tentar usar a lista de compras?",
        "Sente que a funcionalidade de lista de compras é fácil de usar?",
        "Numa escala de 1 a 5, o quanto você teve dificuldade em fazer o assistente entender que queria adicionar algo à lista?",
        "Numa escala de 1 a 5, o quanto foi fácil adicionar itens com quantidades específicas (ex: 2 tomates, 1 kg de arroz)?",
        "Numa escala de 1 a 5, o quanto a funcionalidade da lista de compras é útil no seu dia a dia?",
        "Numa escala de 1 a 5, o quanto você se sentiu frustrado ao tentar usar a lista de compras?",
        "Numa escala de 1 a 5, o quanto você considera fácil de usar a funcionalidade de lista de compras?",
        "A apresentação da lista foi clara e fácil de entender?",
        "A funcionalidade da lista de compras é útil no seu dia a dia?",
        "Já sentiu frustração ao tentar usar a lista de compras?",
        "Sente que a funcionalidade de lista de compras é fácil de usar?",
        "Numa escala de 1 a 5, o quão clara e fácil de entender foi a apresentação da lista de compras?",
        "Numa escala de 1 a 5, o quanto a funcionalidade da lista de compras é útil no seu dia a dia?",
        "Numa escala de 1 a 5, o quanto você se sentiu frustrado ao tentar usar a lista de compras?(Escala negativa: 1 = nenhuma frustração, 5 = muita frustração) ",
        "Numa escala de 1 a 5, o quanto você considera fácil de usar a funcionalidade de lista de compras? ",
        "A funcionalidade da lista de compras é útil no seu dia a dia?",
        "Já sentiu frustração ao tentar usar a lista de compras?",
        "Sente que a funcionalidade de lista de compras é fácil de usar?",
        "Numa escala de 1 a 5, o quanto a funcionalidade da lista de compras é útil no seu dia a dia? ",
        "Numa escala de 1 a 5, o quanto você se sentiu frustrado ao tentar usar a lista de compras?(Escala negativa: 1 = nenhuma frustração, 5 = muita frustração) ",
        "Numa escala de 1 a 5, o quanto você considera fácil de usar a funcionalidade de lista de compras?",
        "O conteúdo do e-mail estava claro e continha todos os itens?",
        "A lista de receitas foi organizada de uma maneira que facilitou sua escolha?",
        "O assistente forneceu uma quantidade adequada de informações sobre cada receita na lista?",
        "O assistente forneceu uma quantidade adequada de informações sobre cada receita na lista?",
        "Numa escala de 1 a 5, o quanto a lista de receitas foi organizada de uma maneira que facilitou sua escolha? "
    ],
    "receitas": [
        "Quando pediu para repetir um passo, o assistente respondeu corretamente?",
        "A repetição do passo foi clara e fácil de entender?",
        "Já sentiu falta de alguma informação importante no passo repetido?",
        "Já se sentiu frustrado com a forma como o assistente repetiu um passo?",
        "Quando pediu para repetir um passo, o assistente respondeu corretamente?",
        "Numa escala de 1 a 5, o quão corretamente o assistente respondeu quando você pediu para repetir um passo?",
        "Numa escala de 1 a 5, o quão clara e fácil de entender foi a repetição do passo feita pelo assistente?",
        "Numa escala de 1 a 5, em que medida você sentiu falta de alguma informação importante na repetição do passo?",
        "Numa escala de 1 a 5, o quanto você se sentiu frustrado com a forma como o assistente repetiu um passo?",
        "O assistente tem-lhe apresentado receitas do seu agrado?",
        "Está satisfeito com a variabilidade de receitas oferecidas pelo assistente ?",
        "Usaria novamente a funçao de pedir uma receita aleatoria?",
        "Considera que a qualidade das receitas apresentadas pelo assistente deveria ser maior?",
        "Numa escala de 1 a 5, o quanto as receitas apresentadas pelo assistente foram do seu agrado?",
        "Numa escala de 1 a 5, o quão satisfeito está com a variabilidade das receitas oferecidas pelo assistente?",
        "Numa escala de 1 a 5, qual a probabilidade de você usar novamente a função de pedir uma receita aleatória?",
        "Numa escala de 1 a 5, em que medida você considera que a qualidade das receitas apresentadas deveria ser maior?",
        "A receita apresentada corresponde ao tipo de prato que pediu ?",
        "A receita fornecida pelo assistente atendeu às suas expectativas?",
        "Usaria novamente a funçao de pedir uma receita específica?",
        "O assistente compreendeu corretamente o tipo de receita que solicitou?",
        "Numa escala de 1 a 5, o quanto a receita apresentada correspondeu ao tipo de prato que você pediu?",
        "Numa escala de 1 a 5, o quanto a receita fornecida atendeu às suas expectativas?",
        "Numa escala de 1 a 5, qual a probabilidade de você usar novamente a função de pedir uma receita específica?",
        " Numa escala de 1 a 5, o quanto o assistente compreendeu corretamente o tipo de receita que você solicitou?",
        "A lista de receitas foi organizada de uma maneira que facilitou sua escolha?",
        "O assistente forneceu uma quantidade adequada de informações sobre cada receita na lista?",
        "O assistente forneceu uma quantidade adequada de informações sobre cada receita na lista?",
        "Numa escala de 1 a 5, o quanto a lista de receitas foi organizada de uma maneira que facilitou sua escolha? ",
        "O assistente foi claro ao explicar o próximo passo?",
        "As instruções fornecidas pelo assistente foram úteis?",
        "Acha que os comandos apresentados lhe foram úteis?",
        "Acha que os comandos disponibilizados foram limitados para as suas questões",
        "Conseguiu perceber o que cada comando faz?",
        "Considera que os comandos estão bem descritos?",
        "Numa escala de 1 a 5, o quanto o assistente foi claro ao explicar o próximo passo?",
        "Numa escala de 1 a 5, o quanto as instruções fornecidas pelo assistente foram úteis?",
        "Numa escala de 1 a 5, o quanto os comandos apresentados foram úteis para você?",
        "Numa escala de 1 a 5, em que medida os comandos disponibilizados foram limitados para responder às suas questões?",
        "Numa escala de 1 a 5, o quanto você conseguiu perceber o que cada comando faz?",
        "Numa escala de 1 a 5, o quão bem descritos estavam os comandos?"
    ],
    "gestao_despensa": [
        # Adicione aqui as perguntas relacionadas com a gestão da despensa
    ]
}
